config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cars do
  resources :reviews, except: :index
  end
  root "cars#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :genre
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_one_attached :image
  attribute :new_image
  
  validates :name, presence: true, length: { maximum: 70 }
  validates :price, presence: true,
    numericality: { 
      only_integer: true,
      greater_than: 1
    }
  validates :publish_date, presence: true
  validates :description, presence: true, length: { maximum: 2000 }

  scope :find_newest_cars, -> (p) { page(p).per(4).order(publish_date: :desc) }

  before_save do
    self.image = new_image if new_image
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :cars
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  belongs_to :user
  enum evaluations: { one: 1, two: 2, three: 3, four: 4, five: 5 }

  validates :evaluation, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  before_action :set_search

  def set_search
    @q = Car.ransack(params[:q])
    @cars = @q.result.with_attached_image.find_newest_cars(params[:page])
  end

  protected 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name, :avatar])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:edit, :update, :destroy]

  def index
    @q = Car.ransack(params[:q])
    @cars = @q.result.with_attached_image.find_newest_cars(params[:page])
  end
  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to @car, notice: "車体を登録しました。"
    else
      render :new
    end
  end

  def show
    @car = Car.with_attached_image.includes(reviews: :user).find(params[:id])
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car, notice: "車体を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path, notice: "車体を削除しました。"
  end

  def index
    @cars = Car.all
  end
  
  private

  def car_params
    params.require(:car).permit(:name, :price, :publish_date, :description, :new_image, :genre_id)
  end
  def set_car
    @car = Car.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_car, only: [:show, :new, :edit]
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  
  def new
    @car = Car.find(params[:car_id])
    @review = Review.new
  end 
  def create
    @review = Review.new(review_params)
    @review.attributes = {
      car_id: params[:car_id],
      user_id: current_user.id
    }
    if @review.save
      redirect_to @review.car, notice: "レビューを更新しました。"
    else
      render :new
    end
  end 

  def show
  end

  def edit
  end  
  def update
    if @review.update(review_params)
      redirect_to @review.car, notice: "レビューを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to @review.car, notice: "レビューを削除しました。"
  end

  private 
  def review_params
    params.require(:review).permit(:title, :body, :evaluation)
  end

  def set_car
    @car = Car.find(params[:car_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
  def show_car_image(car)
    if car.image.attached?
      image_tag car.image.variant(resize: "300x300"), class: "img-thumbnail"
    else
      image_tag "no_image.png", class: "img-thumbnail"
    end
  end
  def show_car_small_image(car)
    if car.image.attached?
      image_tag car.image.variant(resize: "50x50"), class: "img-thumbnail"
    else
      image_tag "no_image.png", class: "img-thumbnail", width: 50
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/_form.html.erb
<%= form_with model: car, local: true do |form| %>
  <%= render "shared/errors", obj: car %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :new_image %><br>
    <%= form.file_field :new_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %><br>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :publish_date %><br>
    <%= form.date_field :publish_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :genre_id %>
    <%= form.collection_select :genre_id, Genre.all, :id, :name , { include_blank: t(".include_blank") },  { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to '戻る', :back, class: "btn btn-secondary" %>
<% end %>

app/views/cars/edit.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <%= render 'form', car: @car %>
</div>

app/views/cars/index.html.erb
<% @cars.each do |car| %>
  <div class="col-md-3 col-sm-6 mb-3">
    <%= show_car_image car %>
    <h4 class="mt-2"><%= link_to car.name, car_path(car) %></h4>
    <div><%= t(".price_yen", price: (number_with_delimiter car.price)) %></div>
    <p><%= car.description %></p>
  </div>
<% end %>

<div class="col-12">
  <%= paginate @cars %>
</div>

app/views/cars/new.html.erb
 <div class="col-md-10 offset-md-1 mt-3">
   <h2 class="text-center"><%= t '.title' %></h2>
   <%= render 'form', car: @car %>
 </div>

app/views/cars/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <div class="row">
  <div class="col-md-4 mb-4">
    <%= show_car_image @car %>
  </div>
  <div class="col-md-8">
    <h2><%= @car.name %></h2>
    <ul>
      <li><b><%= t ".price" %>:</b><%= t(".price_yen", price: (number_with_delimiter @car.price)) %></li>
      <li><b><%= t ".publish_date" %>:</b><%= @car.publish_date %></li>
      <li><b><%= t ".genre" %>: </b><%= @car.genre.try(:name) %></li>
    </ul>
    </div>
  </div>
  <hr>
  <h4><%= t ".description" %></h4>
  <%= simple_format @car.description %>
  <%= link_to t(".edit"), edit_car_path(@car), class: "btn btn-primary" %>
  <%= button_tag t(".delete"), class: "btn btn-warning", data: { toggle: "modal", target: "#delete-car" } %>
  <%= link_to t(".return"), cars_path, class: "btn btn-secondary" %>
  <hr>
  <%= render partial: "reviews/review", collection: @car.reviews %>
</div>
</div>

<div class="modal fade" id="delete-car">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-name" id="exampleModalLabel"><%= t(".modal_name") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".question_car", car: @car.name) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".chancel") %></button>
        <% if user_signed_in? %>
          <%= link_to t(".review_new"), new_book_review_path(@book), class: "btn btn-info" %>
        <% end %>
        <%= link_to t(".delete_action"), car_path(@car), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
      <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: [car, review], local: true do |form| %>
  <%= render "shared/errors", obj: review %>
  <div class="form-group">
    <%= form.label :evaluation %><br>
    <%= form.select :evaluation, Review.evaluations.values, {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to '戻る', car, class: "btn btn-secondary" %>
<% end %>

app/views/reviews/_review.html.erb
<div>
  <div>
    <% if review.user.avatar.attached? %>
      <%= image_tag review.user.avatar.variant(resize: "60x60"), class: "img-thumbnail" %>
    <% else %>
      <%= image_tag "no_image.png", class: "img-thumbnail", width: 60 %>
    <% end %>
    <span><%= review.user.nick_name %></span>
  </div>
  <div>
    <div>
      <span class="text-warning"><%= "★" * review.evaluation %></span>
      <b><%= link_to review.title, car_review_path(review.car, review) %></b>
    </div>
    <small><%= review.created_at.strftime("%Y年%m月%d日") %></small>
  </div>
  <%= simple_format review.body %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-8 offset-md-2 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <div class="mb-3">
    <%= show_car_small_image @car %>
    <span><%= @car.title %></span>
  </div>
  <hr>
  <%= render partial: 'form', locals: { car: @car, review: @review } %>
</div>

app/views/reviews/new.html.erb
<div class="col-md-8 offset-md-2 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <div class="mb-3">
    <%= show_car_small_image @car %>
    <span><%= @car.title %></span>
  </div>
  <hr>
  <%= render partial: 'form', locals: { car: @car, review: @review } %>
</div>

app/views/reviews/show.html.erb
<div class="col-md-8 offset-md-2 mt-5">
  <h2 class="text-center"><%= t ".title" %></h2>
  <div>
    <% if @review.user.avatar.attached? %>
      <%= image_tag @review.user.avatar.variant(resize: "60x60"), class: "img-thumbnail" %>
    <% else %>
      <%= image_tag "no_image.png", class: "img-thumbnail", width: 60 %>
    <% end %>
    <span><%= @review.user.nick_name %></span>
  </div>
  <hr>
  <div>
    <div>
      <span class="text-warning"><%= "★" * @review.evaluation %></span>
      <b><%= @review.title %></b>
    </div>
    <small><%= @review.created_at.strftime("%Y年%m月%d日") %></small>
  </div>
  <%= simple_format @review.body %>
  <% if user_signed_in? && current_user.id == @review.user_id %>
    <%= link_to t(".edit"), edit_car_review_path(@car, @review), class: "btn btn-info" %>
    <%= button_tag t(".delete"), class: "btn btn-warning", data: { toggle: "modal", target: "#delete-review" } %>
  <% end %>
  <%= link_to t(".back"), @car, class: "btn btn-secondary" %>
</div>

<div class="modal fade" id="delete-review">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t(".modal_title") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".question_review", review: @review.title) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".chancel") %></button>
        <%= link_to t(".delete_action"), car_review_path(@car, @review), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
   <div class="alert alert-danger">
     <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
     <ul>
     <% obj.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
   <div class="alert alert-success" role="alert">
     <%= flash.notice %>
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
 <% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to t(".title"), root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".new_car"), new_car_path, class: "nav-link" %>
      </li>
          <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to t(".edit_registration"), edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to t(".new_registration"), new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".log_in"), new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
    </ul>
      <%= search_form_for @q, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.search_field :title_or_description_cont, class: "form-control mr-sm-2" %>
      <%= f.submit t(".search"), class: "btn btn-info my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/shared/_notice.html.erb
<% if flash.notice %>
   <div class="alert alert-success" role="alert">
     <%= flash.notice %>
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
 <% end %>